version: 0.2

phases:
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - aws --version
            - echo $AWS_DEFAULT_REGION
            - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
            - REPOSITORY_URI=809038661221.dkr.ecr.ap-east-1.amazonaws.com/ubuntu
            - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
            - IMAGE_TAG=latest
    build:
        commands:
            - echo Build started on `date`
            - docker version
            - ls
            - cd $CODEBUILD_SRC_DIR/ubuntu
            - echo Building the Docker image...
            - echo $REPOSITORY_URI
            - docker build -t $REPOSITORY_URI:latest .
            - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
    post_build:
        commands:
            - echo Build completed on `date`
            - docker images
            - echo Pushing the Docker images...
            - docker push $REPOSITORY_URI:latest
            - docker push $REPOSITORY_URI:$IMAGE_TAG
            - echo $CODEBUILD_SRC_DIR
            - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > $CODEBUILD_SRC_DIR/imageDetail.json
            - printf '[{"name":"sfx-fargate-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > $CODEBUILD_SRC_DIR/imagedefinitions.json
            - ls -a
            - cat $CODEBUILD_SRC_DIR/imageDetail.json
            - cat $CODEBUILD_SRC_DIR/imagedefinitions.json
